### ISSUE TITLE
Demo not working for users outside uberVU

### ISSUE THREAD

**Issue by RadValentin** [uberVU/github-changelog#17]
## Need

All github users should be able to run the demo and see it working without needing admin access to ubervu
## Solution

Because of the way github works, a user that's not part of ubervu can set issues on the [playground](https://github.com/uberVU/github-changelog-playground) but he won't be able to set labels on that issue. This limitation makes the demo unusable for outside users.
We need to figure out a way will allow any user to run the demo.

Possible solutions:
1. Add a disclaimer on the demo page that informs users about this limitation, and that shows an image(gif) of how the plugin works.
2. Hardcode a default label into the demo and make the plugin pull in all issues from the playground. Even if a user can't set a label, he'll still get a notification with the default label.
3. Add an extra step to the demo instructions with an input field for a repository (defaults to playground). This way a user can run the demo on his own repo. We could also make use of local storage to store this repo name so the demo still works after page reload.

cc: @skidding @catalinmiron

**Comment by ovidiuch** [comment]
1. The gif should be there all the time anyway, a lot more people will see it then are willing to try out the demo flow (even if it worked). No need for disclaimers, it should be self-explanatory
2. We could allow the user to set an empty array for the list of labels, which meant anything goes. But this means no notifications without a label. I remember you said the current styling supports this right?
3. This is cool but I wouldn't go farther with this first iteration. It we do 1. and 2. we should be fine

**Comment by RadValentin** [comment]
Sounds good, 1 + 2 should cover the issue for now. As for styling, this is how it looks when you don't set a label (HTML span element isn't present)
![issues with no labels](https://cloud.githubusercontent.com/assets/3300066/3130501/ec26b6b6-e7f8-11e3-9282-fa883f627c94.png)

**Comment by ovidiuch** [comment]
Is good. Want to take a shot to make the js changes? You need to allow the issues to be added when there's `labels` is set to `[]` [here](https://github.com/uberVU/github-changelog/blob/master/js/changelog.js#L143-L144) and you need to only add the DOM for the label if exists [here](https://github.com/uberVU/github-changelog/blob/master/js/changelog.js#L125-L129) - Maybe also return null here when `labels` is empty [here](https://github.com/uberVU/github-changelog/blob/master/js/changelog.js#L186)

**Comment by RadValentin** [comment]
I'm on it!

**Comment by catalinmiron** [comment]
what about this :+1: 
![github_changelog_enhancement](https://cloud.githubusercontent.com/assets/2805320/3131166/641d7576-e801-11e3-9ddc-c00c9867342b.gif)

cc: @skidding

**Comment by RadValentin** [comment]
I changed it so you can pass in an empty array for `githubLabels` and in this case all issues from the repo will show up. Problem is that since we're not providing any labels to sort by, the plugin won't show labels for issues.

![image](https://cloud.githubusercontent.com/assets/3300066/3174233/9420897e-ebef-11e3-98ff-03679e164724.png)

@skidding any idea on how to get around this? Ideally I'd still like the demo to show some labels so that users see exactly how it should look when integrated into their app.

**Comment by ovidiuch** [comment]
Let's use no labels because it's simpler and more likely to be done by a random user. It does 80% of the job with less effort. We'll show the GIF above the real demo for a quicker impact and with label examples.
