### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by NiGhTTraX** [uberVU/github-changelog#19]
## Need

``` gherkin
As a developer
I want clean maintainable code
So that I can be more productive.
```
## Deliverables

Clean code.
## Solution

Refactor all the things!

**Comment by NiGhTTraX** [comment]
@RadValentin A few things to learn from this:
- use `CamelCase` for naming classes,
- put the time interval for `setTimeout/setInterval` on the same line with the ending `}` of the function,
- use `for (var i = 0, l = v.length; i < l; i++)` when looping through iterables; if you use `i < v.length` then `v.length` will be evaluated every loop,
- use explicit notation when creating elements with jQuery -> `$('<div></div>')` instead of `$('<div>')`,
- `class` is a reserved keyword in JS; if you want to set the class name using the jQuery dict convention then quote it -> `"class"`,
- `$a.append($b.append($c.append($d)).append($e)).append($f)` big no-no,
- use newlines to delimit logical blocks of code.

Optional things to learn from this: :)
- use `that` when storing `this` to use in another closure, it's jQuery unwritten convention,
- declare vars inside their closures; while popular JS book authors advise you against this, it makes code more readable and easier to refactor (you don't have to worry about leftover variables when moving blocks of code).

Things to discuss:
- `$(<div></div>', { "class": "myClass" })` vs `$('<div></div>').addClass("myClass")`,
- `$a.addClass('class1 class2')` vs `$a.addClass('class1').addClass('class2')` (obviously only when the class names are either long or generated dynamically)

@skidding if you don't agree with any of these, feel free to comment :)

**Comment by mihneadb** [comment]
@NiGhTTraX why don't you add some of those tips to the JS best practices doc? :D Thanks!
https://github.com/uberVU/thehole/blob/master/docs/best_practices/javascript.md

**Comment by NiGhTTraX** [comment]
@mihneadb I was just thinking about that! :D

**Comment by mihneadb** [comment]
Sweet! Thanks :D

On Thu, Jun 5, 2014 at 5:08 PM, Andrei Picus notifications@github.com
wrote:

> @mihneadb https://github.com/mihneadb I was just thinking about that! :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uberVU/github-changelog/issues/19#issuecomment-45231383
> .

## 

[image: hootsuite] http://hootsuite.com

_Mihnea Dobrescu-Balaur_
Software Engineer | Hootsuite http://www.hootsuite.com
@mihneadb http://twitter.com/mihneadb
We are hiring in a _big_ way! Apply now http://hootsuite.com/careers

**Comment by RadValentin** [comment]
@NiGhTTraX Thanks for the input, it definitely helps to share knowledge. I was unaware of most of the things you pointed out :)
+1 from me for adding these tips to the best practices documentation
