### ISSUE TITLE
Unify entities and communication

### ISSUE THREAD

**Issue by ovidiuch** [uberVU/github-changelog#9]
Let's see if we can simplify our primitives.

We have both "Notification button" (wiki) and "Notification icon" (readme). Are they two things or the same? Let's use only one if so. I like "button" more.

"Notifications" or "updates"?  I think when it comes to software you have "updates", "notifications" are more related to activities that happen inside the app (Facebook, etc.)

Here's an example of saying nothing:

> ### Notification item
> 
> One element of the notification list.

_Item_, _element_, _list_, even _notification,_ are all abstract words you have to run away from. Then you have joint words _of_, _the_, etc., so no concrete word at all. Element of what? Item of what? List of what? etc.

Here's a sentence that stands by itself:

> The list is made out of app updates that were released since the last time the user hard-refreshed the app. Each update entry corresponds to a closed GitHub issue.

**Comment by RadValentin** [comment]
`README.md` has been updated, thanks @skidding 
I remove the wiki page as it was mostly redundant information, I think we can close this one

**Comment by ovidiuch** [comment]
The project specs are looking better
